title: "PaperSpan Help"
description: "Help Center for PaperSpan"
remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

# (optional) Enable search
search_enabled: true

# (optional) Your site URL (if using custom domain)
url: "https://<your-github-username>.github.io/paperspan-help"

# (optional) Custom navigation (we'll expand this later)
nav:
  - Home: index.md
  - FAQs: faqs.md
  - Apps:
      - Android: apps/android.md
      - iOS: apps/ios.md
