title: "PaperSpan Help"
description: "Help Center for PaperSpan"
remote_theme: pmarsceill/just-the-docs

# Enable search
search_enabled: true

# Site URL
url: "https://paperspan.github.io/help.paperspan.com"

# Navigation (only include files that exist!)
nav:
  - Home: index.md
  - FAQs: faqs.md
  - Apps:
      - Web App: apps/web.md
      - Android App: apps/android.md
      - iOS App: apps/ios.md
      - Chrome Extension: apps/chrome.md
      - Firefox Add-on: apps/firefox.md

